version: "3"

services: 
    app:
        build: 
            context: .
        ports: 
            - "8000:8000"
        volumes: 
            - ./backend:/backend
        command: >
            sh -c "python manage.py wait_for_db &&
                    python manage.py migrate &&
                    python manage.py runserver 0.0.0.0:8000"
        environment: 
            - SECRET_KEY=_b=x&inb(x!ic_er+lvjremkj4g7-+hth8nro4o)zimr7a1+s%
            - DB_HOST=db
            - DB_NAME=election
            - DB_USER=postgres
            - DB_PASS=supersecretpassword
        depends_on: 
            - db
    db:
        image: postgres:12-alpine
        environment: 
            - POSTGRES_DB=election
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=supersecretpassword
    redis:
        image: "redis:alpine"
    celery:
        build: .
        command: celery -A app worker -l info
        volumes:
            - .:/app
        depends_on:
            - db
            - redis