version: "3"

services: 
    app: &app
        build: 
            context: .
        ports: 
            - "8000:8000"
        volumes: 
            - ./backend:/backend
        command: >
            sh -c "python manage.py wait_for_db &&
                    python manage.py migrate &&
                    python manage.py runserver 0.0.0.0:8000"
        environment: 
            - SECRET_KEY=${SECRET_KEY}
            - DB_HOST=${DB_HOST}
            - DB_NAME=${DB_NAME}
            - DB_USER=${DB_USER}
            - DB_PASS=${DB_PASS}
            - INFURA_PROVIDER=${INFURA_PROVIDER}
            - HOST_PRIVATE_KEY=${HOST_PRIVATE_KEY}
            - EMAIL_BACKEND=${EMAIL_BACKEND}
            - EMAIL_HOST=${EMAIL_HOST}
            - EMAIL_PORT=${EMAIL_PORT}
            - EMAIL_HOST_USER=${EMAIL_HOST_USER}
            - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
            - CONTRACT_ADDRESS=${CONTRACT_ADDRESS}
        depends_on: 
            - db
            - redis
            - celery
    db:
        image: postgres:12-alpine
        environment: 
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        volumes:
            - postgresql_data:/var/lib/postgresql/data
        ports:
            - 5432:5432
    redis:
        image: redis:6-alpine
    celery:
        <<: *app
        command: celery -A app worker -l INFO
        ports: []
        depends_on:
            - redis
            - db
    
    # frontend:
    #     build:
    #         context: .
    #         dockerfile: frontend.Dockerfile
    #     ports:
    #         - "3000:3000"
    #     volumes: 
    #         - frontend/node_modules
    #         - ./frontend:/frontend
    #     command: >
    #         sh -c "yarn dev"
    frontend-react:
        build:
            context: .
            dockerfile: frontend.Dockerfile
        ports:
            - "3000:3000"
        stdin_open: true
        volumes: 
            - frontend-react/node_modules
            - ./frontend-react:/frontend-react
        command: >
            sh -c "yarn start"


volumes: 
    postgresql_data: