# Generated by Django 3.1 on 2020-11-09 07:09

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20201001_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='bio',
            field=ckeditor.fields.RichTextField(verbose_name='bio'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='plans',
            field=ckeditor.fields.RichTextField(verbose_name='plans'),
        ),
        migrations.AlterField(
            model_name='party',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='party',
            name='manifesto',
            field=ckeditor.fields.RichTextField(verbose_name='manifesto'),
        ),
        migrations.AlterField(
            model_name='party',
            name='plans',
            field=ckeditor.fields.RichTextField(verbose_name='plans'),
        ),
    ]
