# Generated by Django 3.1 on 2020-11-11 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20201109_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.IntegerField(default=1, verbose_name='contact number'),
            preserve_default=False,
        ),
    ]
